/*------------------------------------------------------------------------------
 *    Copyright 2016 Chris Rink
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *----------------------------------------------------------------------------*/

#include "codegen.h"
#include "../src/bytecode.h"
#include "../src/parser.h"
#include "../src/vm.h"

typedef struct {
    const char *val;         /** Value of the input token */
    ms_VMByteCode *bc;       /** Generated bytecode structure */
} CodeGenResultTuple;

/*
 * TEST DEFINITIONS
 */

MunitTest codegen_tests[] = {
    {
        "/Literals",
        prs_TestCodeGenLiterals,
        NULL,
        NULL,
        MUNIT_TEST_OPTION_NONE,
        NULL
    },
    {
        "/UnaryExpressions",
        prs_TestCodeGenUnaryExprs,
        NULL,
        NULL,
        MUNIT_TEST_OPTION_NONE,
        NULL
    },
    {
        "/BinaryExpressions",
        prs_TestCodeGenBinaryExprs,
        NULL,
        NULL,
        MUNIT_TEST_OPTION_NONE,
        NULL
    },
    {
        "/OperatorPrecedence",
        prs_TestCodeGenExprPrecedence,
        NULL,
        NULL,
        MUNIT_TEST_OPTION_NONE,
        NULL
    },
    {
        "/FunctionCalls",
        prs_TestCodeGenFunctionCalls,
        NULL,
        NULL,
        MUNIT_TEST_OPTION_NONE,
        NULL
    },
    {
        "/QualifiedIdents",
        prs_TestCodeGenQualifiedIdents,
        NULL,
        NULL,
        MUNIT_TEST_OPTION_NONE,
        NULL
    },
    {
        "/GlobalReferences",
        prs_TestCodeGenGlobalReferences,
        NULL,
        NULL,
        MUNIT_TEST_OPTION_NONE,
        NULL
    },
    {
        "/DeleteStatement",
        prs_TestCodeGenDeleteStatement,
        NULL,
        NULL,
        MUNIT_TEST_OPTION_NONE,
        NULL
    },
    {
        "/ForIncrStatements",
        prs_TestCodeGenForIncStatements,
        NULL,
        NULL,
        MUNIT_TEST_OPTION_NONE,
        NULL
    },
    {
        "/ForIterStatements",
        prs_TestCodeGenForIterStatements,
        NULL,
        NULL,
        MUNIT_TEST_OPTION_NONE,
        NULL
    },
    {
        "/ForExprStatements",
        prs_TestCodeGenForExprStatements,
        NULL,
        NULL,
        MUNIT_TEST_OPTION_NONE,
        NULL
    },
    {
        "/IfStatement",
        prs_TestCodeGenIfStatements,
        NULL,
        NULL,
        MUNIT_TEST_OPTION_NONE,
        NULL
    },
    {
        "/ImportStatement",
        prs_TestCodeGenImportStatement,
        NULL,
        NULL,
        MUNIT_TEST_OPTION_NONE,
        NULL
    },
    {
        "/MergeStatement",
        prs_TestCodeGenMergeStatement,
        NULL,
        NULL,
        MUNIT_TEST_OPTION_NONE,
        NULL
    },
    {
        "/ReturnStatement",
        prs_TestCodeGenReturnStatement,
        NULL,
        NULL,
        MUNIT_TEST_OPTION_NONE,
        NULL
    },
    {
        "/FuncDeclaration",
        prs_TestCodeGenFuncDeclaration,
        NULL,
        NULL,
        MUNIT_TEST_OPTION_NONE,
        NULL
    },
    {
        "/Declaration",
        prs_TestCodeGenDeclaration,
        NULL,
        NULL,
        MUNIT_TEST_OPTION_NONE,
        NULL
    },
    {
        "/Assignment",
        prs_TestCodeGenAssignment,
        NULL,
        NULL,
        MUNIT_TEST_OPTION_NONE,
        NULL
    },
    { NULL, NULL, NULL, NULL, MUNIT_TEST_OPTION_NONE, NULL }
};

/*
 * FORWARD DECLARATIONS
 */

static MunitResult CompareByteCode(const ms_VMByteCode *bc1, const ms_VMByteCode *bc2);
static MunitResult CompareValues(const ms_Value *val1, const ms_Value *val2);
static MunitResult TestCodeGenResultTuple(CodeGenResultTuple *tuples, size_t len);
static void CleanByteCode(ms_VMByteCode *bc);

/*
 * AST UTILITY MACROS
 */

#define AST_IDENT_NAME(v)           (dsbuf_new_l(v, sizeof(v)-1))
#define VM_OPC(opc, arg)            ms_VMOpCodeWithArg(opc, arg)
#define VM_FLOAT(v)                 ((ms_Value){ .type = MSVAL_FLOAT, .val = (ms_ValData){ .f = v } })
#define VM_INT(v)                   ((ms_Value){ .type = MSVAL_INT,   .val = (ms_ValData){ .i = v } })
#define VM_STR(v)                   ((ms_Value){ .type = MSVAL_STR,   .val = (ms_ValData){ .s = dsbuf_new_l(v, sizeof(v)-1) } })
#define VM_BOOL(v)                  ((ms_Value){ .type = MSVAL_BOOL,  .val = (ms_ValData){ .b = v } })
#define VM_NULL()                   ((ms_Value){ .type = MSVAL_NULL,  .val = (ms_ValData){ .n = MS_VM_NULL_POINTER } })

/*
 * TEST CASE FUNCTIONS
 */

MunitResult prs_TestCodeGenLiterals(const MunitParameter params[], void *user_data) {
    CodeGenResultTuple exprs[] = {
        {
            .val = "0",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(0),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                },
                .nops = 1, .nvals = 1,
            }
        },
        {
            .val = "3",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(3),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                },
                .nops = 1, .nvals = 1,
            }
        },
        {
            .val = "0.0",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_FLOAT(0.0),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                },
                .nops = 1, .nvals = 1,
            }
        },
        {
            .val = "3.14",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_FLOAT(3.14),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                },
                .nops = 1, .nvals = 1,
            }
        },
        {
            .val = "true",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_BOOL(true),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                },
                .nops = 1, .nvals = 1,
            }
        },
        {
            .val = "false",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_BOOL(false),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                },
                .nops = 1, .nvals = 1,
            }
        },
        {
            .val = "null",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_NULL(),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                },
                .nops = 1, .nvals = 1,
            }
        },
    };

    size_t len = sizeof(exprs) / sizeof(exprs[0]);
    TestCodeGenResultTuple(exprs, len);
    return MUNIT_OK;
}

MunitResult prs_TestCodeGenUnaryExprs(const MunitParameter params[], void *user_data) {
    CodeGenResultTuple exprs[] = {
        {
            .val = "-3",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(3)
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_NEGATE, 0),
                },
                .nops = 2, .nvals = 1,
            }
        },
        {
            .val = "--2.72",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_FLOAT(2.72),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_NEGATE, 0),
                    VM_OPC(OPC_NEGATE, 0),
                },
                .nops = 3, .nvals = 1,
            }
        },
        {
            .val = "!true",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_BOOL(true),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_NOT, 0),
                },
                .nops = 2, .nvals = 1,
            }
        },
        {
            .val = "!!false",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_BOOL(false),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_NOT, 0),
                    VM_OPC(OPC_NOT, 0),
                },
                .nops = 3, .nvals = 1,
            }
        },
        {
            .val = "~792",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(792),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_BITWISE_NOT, 0),
                },
                .nops = 2, .nvals = 1,
            }
        },
        {
            .val = "~~42",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(42),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_BITWISE_NOT, 0),
                    VM_OPC(OPC_BITWISE_NOT, 0),
                },
                .nops = 3, .nvals = 1,
            }
        },
    };

    size_t len = sizeof(exprs) / sizeof(exprs[0]);
    TestCodeGenResultTuple(exprs, len);
    return MUNIT_OK;
}

MunitResult prs_TestCodeGenBinaryExprs(const MunitParameter params[], void *user_data) {
    CodeGenResultTuple exprs[] = {
        {
            .val = "7 + 3.6",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(7),
                    VM_FLOAT(3.6),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_ADD, 0),
                },
                .nops = 3, .nvals = 2,
            }
        },
        {
            .val = "3 + ~3",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(3),
                    VM_INT(3),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_BITWISE_NOT, 0),
                    VM_OPC(OPC_ADD, 0),
                },
                .nops = 4, .nvals = 2,
            }
        },
        {
            .val = "16 - false",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(16),
                    VM_BOOL(false),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_SUBTRACT, 0),
                },
                .nops = 3, .nvals = 2,
            }
        },
        {
            .val = "3 - -3",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(3),
                    VM_INT(3),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_NEGATE, 0),
                    VM_OPC(OPC_SUBTRACT, 0),
                },
                .nops = 4, .nvals = 2,
            }
        },
        {
            .val = "2 * 3.14",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(2),
                    VM_FLOAT(3.14),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_MULTIPLY, 0),
                },
                .nops = 3, .nvals = 2,
            }
        },
        {
            .val = "17 / 8.25",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(17),
                    VM_FLOAT(8.25),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_DIVIDE, 0),
                },
                .nops = 3, .nvals = 2,
            }
        },
        {
            .val = "8.888 \\ 6",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_FLOAT(8.888),
                    VM_INT(6),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_IDIVIDE, 0),
                },
                .nops = 3, .nvals = 2,
            }
        },
        {
            .val = "42 % 8",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(42),
                    VM_INT(8),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_MODULO, 0),
                },
                .nops = 3, .nvals = 2,
            }
        },
        {
            .val = "5.25 ** 2",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_FLOAT(5.25),
                    VM_INT(2),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_EXPONENTIATE, 0),
                },
                .nops = 3, .nvals = 2,
            }
        },
        {
            .val = "5 << 2",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(5),
                    VM_INT(2),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_SHIFT_LEFT, 0),
                },
                .nops = 3, .nvals = 2,
            }
        },
        {
            .val = "183822 >> 4",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(183822),
                    VM_INT(4),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_SHIFT_RIGHT, 0),
                },
                .nops = 3, .nvals = 2,
            }
        },
        {
            .val = "13 & 97",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(13),
                    VM_INT(97),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_BITWISE_AND, 0),
                },
                .nops = 3, .nvals = 2,
            }
        },
        {
            .val = "3 | 15",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(3),
                    VM_INT(15),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_BITWISE_OR, 0),
                },
                .nops = 3, .nvals = 2,
            }
        },
        {
            .val = "53 ^ 7",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(53),
                    VM_INT(7),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_BITWISE_XOR, 0),
                },
                .nops = 3, .nvals = 2,
            }
        },
        {
            .val = "46.12 <= 73",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_FLOAT(46.12),
                    VM_INT(73),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_LE, 0),
                },
                .nops = 3, .nvals = 2,
            }
        },
        {
            .val = "true < 14",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_BOOL(true),
                    VM_INT(14),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_LT, 0),
                },
                .nops = 3, .nvals = 2,
            }
        },
        {
            .val = "33 != 1988",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(33),
                    VM_INT(1988),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_NOT_EQ, 0),
                },
                .nops = 3, .nvals = 2,
            }
        },
        {
            .val = "71 == 0.33",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(71),
                    VM_FLOAT(0.33),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_EQ, 0),
                },
                .nops = 3, .nvals = 2,
            }
        },
        {
            .val = "81.3 > 90",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_FLOAT(81.3),
                    VM_INT(90),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_GT, 0),
                },
                .nops = 3, .nvals = 2,
            }
        },
        {
            .val = "1000 >= 10000",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(1000),
                    VM_INT(10000),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_GE, 0),
                },
                .nops = 3, .nvals = 2,
            }
        },

        {
            .val = "true && false",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_BOOL(true),
                    VM_BOOL(false),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_AND, 0),
                },
                .nops = 3, .nvals = 2,
            }
        },
        {
            .val = "true && !true",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_BOOL(true),
                    VM_BOOL(true),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_NOT, 0),
                    VM_OPC(OPC_AND, 0),
                },
                .nops = 4, .nvals = 2,
            }
        },
        {
            .val = "1 || null",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(1),
                    VM_NULL(),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_OR, 0),
                },
                .nops = 3, .nvals = 2,
            }
        },
    };

    size_t len = sizeof(exprs) / sizeof(exprs[0]);
    TestCodeGenResultTuple(exprs, len);
    return MUNIT_OK;
}

MunitResult prs_TestCodeGenExprPrecedence(const MunitParameter params[], void *user_data) {
    CodeGenResultTuple exprs[] = {
        {
            .val = "false || false && true",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_BOOL(false),
                    VM_BOOL(false),
                    VM_BOOL(true),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_AND, 0),
                    VM_OPC(OPC_OR, 0),
                },
                .nops = 5, .nvals = 3,
            }
        },
        {
            .val = "(false || false) && true",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_BOOL(false),
                    VM_BOOL(false),
                    VM_BOOL(true),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_OR, 0),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_AND, 0),
                },
                .nops = 5, .nvals = 3,
            }
        },
        {
            .val = "(false || !false) && true",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_BOOL(false),
                    VM_BOOL(false),
                    VM_BOOL(true),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_NOT, 0),
                    VM_OPC(OPC_OR, 0),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_AND, 0),
                },
                .nops = 6, .nvals = 3,
            }
        },
        {
            .val = "false == false != true",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_BOOL(false),
                    VM_BOOL(false),
                    VM_BOOL(true),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_EQ, 0),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_NOT_EQ, 0),
                },
                .nops = 5, .nvals = 3,
            }
        },
        {
            .val = "false == (false != true)",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_BOOL(false),
                    VM_BOOL(false),
                    VM_BOOL(true),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_NOT_EQ, 0),
                    VM_OPC(OPC_EQ, 0),
                },
                .nops = 5, .nvals = 3,
            }
        },
        {
            .val = "7 > 3.6 < 8",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(7),
                    VM_FLOAT(3.6),
                    VM_INT(8),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_GT, 0),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_LT, 0),
                },
                .nops = 5, .nvals = 3,
            }
        },
        {
            .val = "7 > (3.6 < 8)",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(7),
                    VM_FLOAT(3.6),
                    VM_INT(8),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_LT, 0),
                    VM_OPC(OPC_GT, 0),
                },
                .nops = 5, .nvals = 3,
            }
        },
        {
            .val = "7 > 3.6 >= 8",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(7),
                    VM_FLOAT(3.6),
                    VM_INT(8),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_GT, 0),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_GE, 0),
                },
                .nops = 5, .nvals = 3,
            }
        },
        {
            .val = "7 | 2 & 15",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(7),
                    VM_INT(2),
                    VM_INT(15),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_BITWISE_AND, 0),
                    VM_OPC(OPC_BITWISE_OR, 0),
                },
                .nops = 5, .nvals = 3,
            }
        },
        {
            .val = "7 ^ 2 & 15",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(7),
                    VM_INT(2),
                    VM_INT(15),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_BITWISE_AND, 0),
                    VM_OPC(OPC_BITWISE_XOR, 0),
                },
                .nops = 5, .nvals = 3,
            }
        },
        {
            .val = "7 ^ 2 | 15",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(7),
                    VM_INT(2),
                    VM_INT(15),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_BITWISE_XOR, 0),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_BITWISE_OR, 0),
                },
                .nops = 5, .nvals = 3,
            }
        },
        {
            .val = "7 ^ (2 | 15)",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(7),
                    VM_INT(2),
                    VM_INT(15),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_BITWISE_OR, 0),
                    VM_OPC(OPC_BITWISE_XOR, 0),
                },
                .nops = 5, .nvals = 3,
            }
        },
        {
            .val = "(7 | 2) & 15",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(7),
                    VM_INT(2),
                    VM_INT(15),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_BITWISE_OR, 0),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_BITWISE_AND, 0),
                },
                .nops = 5, .nvals = 3,
            }
        },
        {
            .val = "(7 | 2) & ~15",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(7),
                    VM_INT(2),
                    VM_INT(15),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_BITWISE_OR, 0),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_BITWISE_NOT, 0),
                    VM_OPC(OPC_BITWISE_AND, 0),
                },
                .nops = 6, .nvals = 3,
            }
        },
        {
            .val = "~(7 | 2) & 15",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(7),
                    VM_INT(2),
                    VM_INT(15),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_BITWISE_OR, 0),
                    VM_OPC(OPC_BITWISE_NOT, 0),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_BITWISE_AND, 0),
                },
                .nops = 6, .nvals = 3,
            }
        },
        {
            .val = "15 | 1 << 2",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(15),
                    VM_INT(1),
                    VM_INT(2),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_SHIFT_LEFT, 0),
                    VM_OPC(OPC_BITWISE_OR, 0),
                },
                .nops = 5, .nvals = 3,
            }
        },
        {
            .val = "(15 | 1) << 2",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(15),
                    VM_INT(1),
                    VM_INT(2),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_BITWISE_OR, 0),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_SHIFT_LEFT, 0),
                },
                .nops = 5, .nvals = 3,
            }
        },
        {
            .val = "7 + 3.6 - 8",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(7),
                    VM_FLOAT(3.6),
                    VM_INT(8),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_ADD, 0),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_SUBTRACT, 0),
                },
                .nops = 5, .nvals = 3,
            }
        },
        {
            .val = "7 + (3.6 - 8)",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(7),
                    VM_FLOAT(3.6),
                    VM_INT(8),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_SUBTRACT, 0),
                    VM_OPC(OPC_ADD, 0),
                },
                .nops = 5, .nvals = 3,
            }
        },
        {
            .val = "7 + (3.6 - -8)",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(7),
                    VM_FLOAT(3.6),
                    VM_INT(8),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_NEGATE, 0),
                    VM_OPC(OPC_SUBTRACT, 0),
                    VM_OPC(OPC_ADD, 0),
                },
                .nops = 6, .nvals = 3,
            }
        },
        {
            .val = "(7 + 3.6) - -8",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(7),
                    VM_FLOAT(3.6),
                    VM_INT(8),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_ADD, 0),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_NEGATE, 0),
                    VM_OPC(OPC_SUBTRACT, 0),
                },
                .nops = 6, .nvals = 3,
            }
        },
        {
            .val = "7 + 3.6 * -8",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(7),
                    VM_FLOAT(3.6),
                    VM_INT(8),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_NEGATE, 0),
                    VM_OPC(OPC_MULTIPLY, 0),
                    VM_OPC(OPC_ADD, 0),
                },
                .nops = 6, .nvals = 3,
            }
        },
        {
            .val = "7 / 3.6 * -8",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(7),
                    VM_FLOAT(3.6),
                    VM_INT(8),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_DIVIDE, 0),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_NEGATE, 0),
                    VM_OPC(OPC_MULTIPLY, 0),
                },
                .nops = 6, .nvals = 3,
            }
        },
        {
            .val = "7 \\ 3.6 % -8",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(7),
                    VM_FLOAT(3.6),
                    VM_INT(8),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_IDIVIDE, 0),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_NEGATE, 0),
                    VM_OPC(OPC_MODULO, 0),
                },
                .nops = 6, .nvals = 3,
            }
        },
        {
            .val = "7 ** 4 ** 2",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(7),
                    VM_INT(4),
                    VM_INT(2),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_EXPONENTIATE, 0),
                    VM_OPC(OPC_EXPONENTIATE, 0),
                },
                .nops = 5, .nvals = 3,
            }
        },
        {
            .val = "(7 ** 4) ** 2",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(7),
                    VM_INT(4),
                    VM_INT(2),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_EXPONENTIATE, 0),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_EXPONENTIATE, 0),
                },
                .nops = 5, .nvals = 3,
            }
        },
        {
            .val = "7 ** 4 * 2",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(7),
                    VM_INT(4),
                    VM_INT(2),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_MULTIPLY, 0),
                    VM_OPC(OPC_EXPONENTIATE, 0),
                },
                .nops = 5, .nvals = 3,
            }
        },
        {
            .val = "7 ** 4 + 2",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(7),
                    VM_INT(4),
                    VM_INT(2),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_EXPONENTIATE, 0),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_ADD, 0),
                },
                .nops = 5, .nvals = 3,
            }
        },
        {
            .val = "7 ** (4 + 2)",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_INT(7),
                    VM_INT(4),
                    VM_INT(2),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_ADD, 0),
                    VM_OPC(OPC_EXPONENTIATE, 0),
                },
                .nops = 5, .nvals = 3,
            }
        },
    };

    size_t len = sizeof(exprs) / sizeof(exprs[0]);
    TestCodeGenResultTuple(exprs, len);
    return MUNIT_OK;
}

MunitResult prs_TestCodeGenFunctionCalls(const MunitParameter params[], void *user_data) {
    CodeGenResultTuple exprs[] = {
        {
            .val = "$len()",
            .bc = &(ms_VMByteCode){
                .values = NULL,
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_GET_NAME, 0),
                    VM_OPC(OPC_CALL, 0),
                },
                .idents = ((DSBuffer*[]){
                    AST_IDENT_NAME("$len"),
                }),
                .nops = 2, .nvals = 0, .nidents = 1
            }
        },
        {
            .val = "foo()",
            .bc = &(ms_VMByteCode){
                .values = NULL,
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_GET_NAME, 0),
                    VM_OPC(OPC_CALL, 0),
                },
                .idents = ((DSBuffer*[]){
                    AST_IDENT_NAME("foo"),
                }),
                .nops = 2, .nvals = 0, .nidents = 1
            }
        },
        {
            .val = "$len(\"string\")",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_STR("string"),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_GET_NAME, 0),
                    VM_OPC(OPC_CALL, 1),
                },
                .idents = ((DSBuffer*[]){
                    AST_IDENT_NAME("$len"),
                }),
                .nops = 3, .nvals = 1, .nidents = 1
            }
        },
        {
            .val = "foo(\"string\")",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_STR("string"),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_GET_NAME, 0),
                    VM_OPC(OPC_CALL, 1),
                },
                .idents = ((DSBuffer*[]){
                    AST_IDENT_NAME("foo"),
                }),
                .nops = 3, .nvals = 1, .nidents = 1
            }
        },
        {
            .val = "foo()()",
            .bc = &(ms_VMByteCode){
                .values = NULL,
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_GET_NAME, 0),
                    VM_OPC(OPC_CALL, 0),
                    VM_OPC(OPC_CALL, 0),
                },
                .idents = ((DSBuffer*[]){
                    AST_IDENT_NAME("foo"),
                }),
                .nops = 3, .nvals = 0, .nidents = 1
            }
        },
        {
            .val = "bar(\"baz\")()",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_STR("baz"),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_GET_NAME, 0),
                    VM_OPC(OPC_CALL, 1),
                    VM_OPC(OPC_CALL, 0),
                },
                .idents = ((DSBuffer*[]){
                    AST_IDENT_NAME("bar"),
                }),
                .nops = 4, .nvals = 1, .nidents = 1
            }
        },
    };

    size_t len = sizeof(exprs) / sizeof(exprs[0]);
    TestCodeGenResultTuple(exprs, len);
    return MUNIT_OK;
}

MunitResult prs_TestCodeGenQualifiedIdents(const MunitParameter params[], void *user_data) {
    CodeGenResultTuple exprs[] = {
        {
            .val = "name",
            .bc = &(ms_VMByteCode){
                .values = NULL,
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_GET_NAME, 0),
                },
                .idents = ((DSBuffer*[]){
                    AST_IDENT_NAME("name"),
                }),
                .nops = 1, .nvals = 0, .nidents = 1
            }
        },
        {
            .val = "name.first",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_STR("first"),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_GET_NAME, 0),
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_GET_ATTR, 1),
                },
                .idents = ((DSBuffer*[]){
                    AST_IDENT_NAME("name"),
                }),
                .nops = 3, .nvals = 1, .nidents = 1
            }
        },
        {
            .val = "name[\"first\"]",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_STR("first"),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_GET_NAME, 0),
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_GET_ATTR, 1),
                },
                .idents = ((DSBuffer*[]){
                    AST_IDENT_NAME("name"),
                }),
                .nops = 3, .nvals = 1, .nidents = 1
            }
        },
        {
            .val = "name.first.second.third",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_STR("first"),
                    VM_STR("second"),
                    VM_STR("third"),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_GET_NAME, 0),
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_GET_ATTR, 1),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_GET_ATTR, 1),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_GET_ATTR, 1),
                },
                .idents = ((DSBuffer*[]){
                    AST_IDENT_NAME("name"),
                }),
                .nops = 7, .nvals = 3, .nidents = 1
            },
            .val = "name[\"first\", \"second\"].third",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_STR("first"),
                    VM_STR("second"),
                    VM_STR("third"),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_GET_NAME, 0),
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_GET_ATTR, 2),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_GET_ATTR, 1),
                },
                .idents = ((DSBuffer*[]){
                    AST_IDENT_NAME("name"),
                }),
                .nops = 6, .nvals = 3, .nidents = 1
            },
        },
    };

    size_t len = sizeof(exprs) / sizeof(exprs[0]);
    TestCodeGenResultTuple(exprs, len);
    return MUNIT_OK;
}

MunitResult prs_TestCodeGenGlobalReferences(const MunitParameter params[], void *user_data) {
    CodeGenResultTuple exprs[] = {
        {
            .val = "@glo",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_STR("@glo"),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_GET_GLO, 0),
                },
                .idents = NULL,
                .nops = 2, .nvals = 1, .nidents = 0
            }
        },
        {
            .val = "@glo.first",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_STR("@glo"),
                    VM_STR("first"),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_GET_GLO, 1),
                },
                .idents = NULL,
                .nops = 3, .nvals = 2, .nidents = 0
            }
        },
        {
            .val = "@glo.first.second",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_STR("@glo"),
                    VM_STR("first"),
                    VM_STR("second"),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_GET_GLO, 2),
                },
                .idents = NULL,
                .nops = 4, .nvals = 3, .nidents = 0
            }
        },
        {
            .val = "@glo.first.second[\"third\"]",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_STR("@glo"),
                    VM_STR("first"),
                    VM_STR("second"),
                    VM_STR("third"),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_PUSH, 3),
                    VM_OPC(OPC_GET_GLO, 3),
                },
                .idents = NULL,
                .nops = 5, .nvals = 4, .nidents = 0
            }
        },
        {
            .val = "@glo[\"first\"]",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_STR("@glo"),
                    VM_STR("first"),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_GET_GLO, 1),
                },
                .idents = NULL,
                .nops = 3, .nvals = 2, .nidents = 0
            }
        },
        {
            .val = "@glo[\"first\", \"second\"]",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_STR("@glo"),
                    VM_STR("first"),
                    VM_STR("second"),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_GET_GLO, 2),
                },
                .idents = NULL,
                .nops = 4, .nvals = 3, .nidents = 0
            }
        },
        {
            .val = "@glo[\"first\", \"second\"].third",
            .bc = &(ms_VMByteCode){
                .values = (ms_Value[]){
                    VM_STR("@glo"),
                    VM_STR("first"),
                    VM_STR("second"),
                    VM_STR("third"),
                },
                .code = (ms_VMOpCode[]){
                    VM_OPC(OPC_PUSH, 0),
                    VM_OPC(OPC_PUSH, 1),
                    VM_OPC(OPC_PUSH, 2),
                    VM_OPC(OPC_PUSH, 3),
                    VM_OPC(OPC_GET_GLO, 3),
                },
                .idents = NULL,
                .nops = 5, .nvals = 4, .nidents = 0
            }
        },
    };

    size_t len = sizeof(exprs) / sizeof(exprs[0]);
    TestCodeGenResultTuple(exprs, len);
    return MUNIT_OK;
}

MunitResult prs_TestCodeGenDeleteStatement(const MunitParameter params[], void *user_data) {
    return MUNIT_OK;
}

MunitResult prs_TestCodeGenForIncStatements(const MunitParameter params[], void *user_data) {
    return MUNIT_OK;
}

MunitResult prs_TestCodeGenForIterStatements(const MunitParameter params[], void *user_data) {
    return MUNIT_OK;
}

MunitResult prs_TestCodeGenForExprStatements(const MunitParameter params[], void *user_data)  {
    return MUNIT_OK;
}

MunitResult prs_TestCodeGenIfStatements(const MunitParameter params[], void *user_data) {
    return MUNIT_OK;
}

MunitResult prs_TestCodeGenImportStatement(const MunitParameter params[], void *user_data) {
    return MUNIT_OK;
}

MunitResult prs_TestCodeGenMergeStatement(const MunitParameter params[], void *user_data) {
    return MUNIT_OK;
}

MunitResult prs_TestCodeGenReturnStatement(const MunitParameter params[], void *user_data) {
    return MUNIT_OK;
}

MunitResult prs_TestCodeGenFuncDeclaration(const MunitParameter params[], void *user_data) {
    return MUNIT_OK;
}

MunitResult prs_TestCodeGenDeclaration(const MunitParameter params[], void *user_data) {
    return MUNIT_OK;
}

MunitResult prs_TestCodeGenAssignment(const MunitParameter params[], void *user_data) {
    return MUNIT_OK;
}

/*
 * COMPARISON FUNCTIONS
 */

static MunitResult CompareByteCode(const ms_VMByteCode *bc1, const ms_VMByteCode *bc2) {
    munit_assert_non_null(bc1);
    munit_assert_non_null(bc2);
    munit_assert_cmp_int(bc1->nops, ==, bc2->nops);
    munit_assert_cmp_int(bc1->nvals, ==, bc2->nvals);

    for (size_t i = 0; i < bc1->nops; i++) {
        ms_VMOpCode opc1 = bc1->code[i];
        ms_VMOpCode opc2 = bc2->code[i];
        const char *nm1 = ms_VMOpCodeToString(opc1);
        const char *nm2 = ms_VMOpCodeToString(opc2);
        ms_VMOpCodeType type1 = ms_VMOpCodeGetCode(opc1);
        ms_VMOpCodeType type2 = ms_VMOpCodeGetCode(opc2);
        int arg1 = ms_VMOpCodeGetArg(opc1);
        int arg2 = ms_VMOpCodeGetArg(opc2);

        munit_logf(MUNIT_LOG_INFO, "  opc1='%s'", nm1);
        munit_logf(MUNIT_LOG_INFO, "  opc2='%s'", nm2);
        munit_assert_cmp_int(type1, ==, type2);
        munit_assert_cmp_int(arg1, ==, arg2);
        munit_assert_cmp_int(opc1, ==, opc2);
    }

    for (size_t i = 0; i < bc1->nvals; i++) {
        CompareValues(&bc1->values[i], &bc2->values[i]);
    }

    for (size_t i = 0; i < bc1->nidents; i++) {
        const char *s1 = dsbuf_char_ptr(bc1->idents[i]);
        const char *s2 = dsbuf_char_ptr(bc2->idents[i]);
        munit_logf(MUNIT_LOG_INFO, "  ident1='%s'", s1);
        munit_logf(MUNIT_LOG_INFO, "  ident2='%s'", s2);
        munit_assert_string_equal(s1, s2);
    }

    return MUNIT_OK;
}

static MunitResult CompareValues(const ms_Value *val1, const ms_Value *val2) {
    munit_assert_non_null(val1);
    munit_assert_non_null(val2);

    munit_assert_cmp_int(val1->type, ==, val2->type);
    switch (val1->type) {
        case MSVAL_FLOAT:
            munit_assert_cmp_double(val1->val.f, ==, val2->val.f);
            break;
        case MSVAL_INT:
            munit_assert_cmp_int(val1->val.i, ==, val2->val.i);
            break;
        case MSVAL_STR:
            munit_assert_true(dsbuf_equals(val1->val.s, val2->val.s));
            break;
        case MSVAL_BOOL:
            munit_assert(val1->val.b == val2->val.b);
            break;
        case MSVAL_NULL:
            munit_assert(val1->val.n == val2->val.n);
            break;
        case MSVAL_FUNC:
            munit_assert(false);
            break;
    }

    return MUNIT_OK;
}

static MunitResult TestCodeGenResultTuple(CodeGenResultTuple *tuples, size_t len) {
    ms_Parser *prs = ms_ParserNew();
    munit_assert_non_null(prs);

    for (size_t i = 0; i < len; i++) {
        CodeGenResultTuple *tuple = &tuples[i];
        ms_ParserInitString(prs, tuple->val);
        munit_logf(MUNIT_LOG_INFO, "  code='%s'", tuple->val);

        const ms_AST *ast;
        ms_VMByteCode *code;
        const ms_ParseError *err;
        ms_ParseResult pres = ms_ParserParse(prs, &code, &ast, &err);
        if (err) { munit_logf(MUNIT_LOG_INFO, "err = %s", err->msg); }

        munit_assert_cmp_int(pres, !=, PARSE_ERROR);
        munit_assert_non_null(code);

        CompareByteCode(code, tuple->bc);
        ms_VMByteCodeDestroy(code);
        CleanByteCode(tuple->bc);
    }

    ms_ParserDestroy(prs);
    return MUNIT_OK;
}

/*
 * CLEAN UP FUNCTIONS
 */

static void CleanByteCode(ms_VMByteCode *bc) {
    for (size_t i = 0; i < bc->nvals; i++) {
        if (bc->values[i].type == MSVAL_STR) {
            dsbuf_destroy(bc->values[i].val.s);
            bc->values[i].val.s = NULL;
        }
    }

    for (size_t i = 0; i < bc->nidents; i++) {
        dsbuf_destroy(bc->idents[i]);
        bc->idents[i] = NULL;
    }
}
